version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 api_webstore_core.wsgi:application --chdir api_webstore/
    env_file:
      .env.dev # ./.env.dev analog
#    volumes:
#      - .:/app # всі дані з поточного каталогу на моєму компі будуть монтуватися в контейнер. це будуть спільні дані. відкрити доступ контейнера до цих даних та змінювати їх
#      - /app/modules
    depends_on:
      - db_postgresql

  db_postgresql:
    container_name: database_for_app
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_webstore_db
    volumes:
      - db_data:/var/lib/postgresql/data # те що на хості:те що в контейнері


volumes:
  db_data: