version: "3"

services:

  app:
    build: .
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 api_webstore_core.wsgi:application --chdir api_webstore/
    depends_on:
      - db_postgresql

  db_postgresql:
    container_name: database_for_app
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_webstore_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: