# Generated by Django 4.2 on 2023-11-02 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('online_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='online_payment', to='product.order'),
        ),
    ]
