# Generated by Django 4.1.6 on 2023-02-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='basket',
            field=models.ManyToManyField(blank=True, default=None, to='base_app.position'),
        ),
    ]
