# Generated by Django 4.2 on 2023-06-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base_app.position', verbose_name='Position'),
        ),
    ]
