# Generated by Django 4.2 on 2023-06-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_client_user_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='base_app.client', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='base_app.categories', verbose_name='Category '),
        ),
    ]
