# Generated by Django 4.2 on 2023-06-08 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_order_client_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date create'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
